version: "3.8"
services:
  visuallyimpairedbot:
    build: .
    restart: unless-stopped
    command: "bash -c 'mount'"
    tmpfs: 
      - /home/visuallyimpairedbot/ramdisk
    volumes:
      - ./pythonfiles/:/home/visuallyimpairedbot/pythonfiles/
      - ./db/:/home/visuallyimpairedbot/db/
      - ./secrets/:/home/visuallyimpairedbot/secrets/
    command: bash -c "chmod -R 666 ./ramdisk"
    command: bash -c "python3 -u ./pythonfiles/main.py"
    